name: ausBlackMarketingExtras
version: '${version}'

main: plugin.ausBlackMarketingExtras.AusBlackMarketingExtras
bootstrapper: plugin.ausBlackMarketingExtras.AusBlackMarketingExtrasBootstrap
loader: plugin.ausBlackMarketingExtras.AusBlackMarketingExtrasLoader
api-version: '1.21'
load: POSTWORLD

authors: [ ZzPowerTechzZ ]

dependencies:
  server:
    AxDarkAuctions:
      load: BEFORE
      required: true
    WorldEdit:
      load: BEFORE
      required: true
    Citizens:
      load: BEFORE
      required: true
