name: ausBlackMarketingExtras
version: '${version}'

main: plugin.ausBlackMarketingExtras.AusBlackMarketingExtras
bootstrapper: plugin.ausBlackMarketingExtras.AusBlackMarketingExtrasBootstrap
loader: plugin.ausBlackMarketingExtras.AusBlackMarketingExtrasLoader
api-version: '26.1.2'
load: POSTWORLD

authors: [ ZzPowerTechzZ ]
